ChangedUtcTimestamp: 2025-11-18T13:39:01.8604937Z
ConnectionLines:
- ItemStart: 131080
  ItemStop: 131072
- ItemStart: 171765471
  ItemStop: 244601728
- ItemStart: 131073
  ItemStop: 1012489383
PublishedUtcTimestamp: 2020-03-27T12:19:53.0000000Z
SavedInVersion: 5.6.5000.0
TransferObjects:
- ChangedUTCTimestamp: 2020-03-27T15:23:58.0000000Z
  GridSnapPixel: 17
  Groups:
  - GroupType: 18005
    Name: Rest-Host
  - Groups:
    - Items:
      - Direction: input
        LocalId: 131072
        Name: Authorization
        _clrType:
        - inray.OPCRouter.RestPlugIn.Shared.Config.RestParameterItem, inray.OPCRouter4.RestPlugIn
      Name: HttpHeader
    GroupType: 18003
    Name: Request-Parameter
  - GroupType: 18004
    Name: Response-Headers
  - GroupType: 18006
    Name: Request-Body
  - GroupType: 18007
    Items:
    - Direction: output
      LocalId: 131073
      Name: Body
      ParameterType: ResposeBodyItem
      _clrType:
      - inray.OPCRouter.RestPlugIn.Shared.Config.RestParameterItem, inray.OPCRouter4.RestPlugIn
    - Direction: output
      LocalId: 131074
      Name: Status code
      _clrType:
      - inray.OPCRouter.RestPlugIn.Shared.Config.RestParameterItem, inray.OPCRouter4.RestPlugIn
    - Direction: output
      LocalId: 131075
      Name: Status text
      _clrType:
      - inray.OPCRouter.RestPlugIn.Shared.Config.RestParameterItem, inray.OPCRouter4.RestPlugIn
    Name: Response
  - Name: Request-File-Parameter
    _clrType:
    - inray.OPCRouter.RestPlugIn.Client.Config.RequestFileItemsGroup, inray.OPCRouter4.RestPlugIn
  LocalId: 131072
  PlugIn: 2402021319-350676956-50130D05-00006E59
  PosX: 640
  PosY: 160
  RequestFormat: application/json
  URL: "${rest_data_request_to_url}"
  _clrType:
  - inray.OPCRouter.RestPlugIn.Client.Config.RestTransferObjectConfig, inray.OPCRouter4.RestPlugIn
- ChangedUTCTimestamp: 2020-03-27T15:26:23.0000000Z
  Delay: 5000ms
  LocalId: 131073
  PlugIn: BasePlugInConfig
  PosX: 20
  PosY: 20
  _clrType:
  - inray.OPCRouter.BasePlugIn.Config.TimeTrigger.TimeTriggerConfig, inray.OPCRouter4.BasePlugIn
- ChangedUTCTimestamp: 2020-03-27T15:26:12.0000000Z
  GridSnapPixel: 5
  Groups:
  - Items:
    - LocalId: 171765471
      Name: ${bearer_token_variable_name}
      VariableId: 9500dabc-0a5e-4949-a102-37874f3148bb
      _clrType:
      - inray.OPCRouter.VariablesPlugIn.Runtime.VariablesTransferObjectItem, inray.OPCRouter4.VariablesPlugIn
  LocalId: 131074
  PlugIn: VariablesPlugInConfig
  PosX: 20
  PosY: 220
  _clrType:
  - inray.OPCRouter.VariablesPlugIn.Config.VariablesTransferObjectConfig, inray.OPCRouter4.VariablesPlugIn
- ChangedUTCTimestamp: 2020-03-27T15:23:58.0000000Z
  GridSnapPixel: 10
  Groups:
  - GroupType: 1050
    Items:
    - Direction: input
      LocalId: 244601728
      Name: Token
    Name: Variablen
  - GroupType: 1051
    Items:
    - Direction: output
      LocalId: 131080
      Name: Output value
    Name: Result
  LocalId: 131076
  PlugIn: BasePlugInConfig
  PosX: 240
  PosY: 180
  StringToParse: CONCATENATE("Bearer ", "Token")
  _clrType:
  - inray.OPCRouter.BasePlugIn.Config.Calculator.TORechnerTransferObjectConfig, inray.OPCRouter4.BasePlugIn
- ChangedUTCTimestamp: 2020-03-27T15:23:58.0000000Z
  GridSnapPixel: 5
  Groups:
  - Items:
    - LocalId: 1012489383
      Name: ${request_data_variable_name}
      VariableId: a571802a-7a51-47f3-bfbf-22cc5d8fba3e
      _clrType:
      - inray.OPCRouter.VariablesPlugIn.Runtime.VariablesTransferObjectItem, inray.OPCRouter4.VariablesPlugIn
  LocalId: 131077
  PlugIn: VariablesPlugInConfig
  PosX: 1020
  PosY: 300
  _clrType:
  - inray.OPCRouter.VariablesPlugIn.Config.VariablesTransferObjectConfig, inray.OPCRouter4.VariablesPlugIn
