ChangedUtcTimestamp: 0001-01-01T00:00:00.0000000Z
ConnectionLines:
- ItemStart: 1486979360
  ItemStop: 1427967031
PublishedUtcTimestamp: 0001-01-01T00:00:00.0000000Z
SavedInVersion: 5.6.50.0
TransferObjects:
- ChangedUTCTimestamp: 2023-09-26T06:32:02.0080000Z
  Cycle: 10000ms
  LocalId: 927110513
  PlugIn: BasePlugInConfig
  PosX: 340
  PosY: 180
  _clrType:
  - inray.OPCRouter.BasePlugIn.Config.TimeTrigger.TimeTriggerConfig, inray.OPCRouter4.BasePlugIn
- ChangedUTCTimestamp: 2023-09-26T06:32:41.6410000Z
  ConfigType: 3001
  Groups:
  - Items:
    - ForceType: Default
      LocalId: 1427967031
      Name: bp=Objects/2:Maschinen/2:H02/2:Störungsbit;
      OPCAddress: bp=Objects/2:Maschinen/2:H02/2:Störungsbit;
      _clrType:
      - inray.OPCRouter.OPCPlugIn.Runtime.OPCTransferObjectItem, inray.OPCRouter4.OPCPlugIn
    Name: Items
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcRegularItemsGroup, inray.OPCRouter4.OPCPlugIn
  - Name: Value Timestamp
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcValueTimestampGroup, inray.OPCRouter4.OPCPlugIn
  - Name: Quality ID
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcQualityIntGroup, inray.OPCRouter4.OPCPlugIn
  - Name: Quality string
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcQualityStringGroup, inray.OPCRouter4.OPCPlugIn
  LocalId: 1727659371
  PlugIn: UAServer2408301209-223846937-1801FB34-00002707
  PlugInType: 3100
  PosX: 880
  PosY: 420
  _clrType:
  - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObjectConfig, inray.OPCRouter4.OPCPlugIn
- ChangedUTCTimestamp: 2023-09-26T06:43:58.2160000Z
  Groups:
  - Name: Variables
    _clrType:
    - inray.OPCRouter.BasePlugIn.Config.Calculator.TORechnerVariablesGroup, inray.OPCRouter4.BasePlugIn
  - Items:
    - Direction: output
      LocalId: 1486979360
      Name: Output value
    Name: Result
    _clrType:
    - inray.OPCRouter.BasePlugIn.Config.Calculator.TORechnerResultGroup, inray.OPCRouter4.BasePlugIn
  LocalId: 954810038
  PlugIn: BasePlugInConfig
  PosX: 400
  PosY: 420
  StringToParse: IF(RANDBETWEEN(0, 100) > 95, true, false)
  _clrType:
  - inray.OPCRouter.BasePlugIn.Config.Calculator.TORechnerTransferObjectConfig, inray.OPCRouter4.BasePlugIn
