ChangedUtcTimestamp: 2024-10-16T11:40:55.0510000Z
ConnectionLines:
- ItemStart: 2059240501
  ItemStop: 713674027
- ItemStart: 1514016551
  ItemStop: 2061007296
- ItemStart: 1343061374
  ItemStop: 1904181876
- ItemStart: 2059240501
  ItemStop: 1767872708
PublishedUtcTimestamp: 0001-01-01T00:00:00.0000000Z
SavedInVersion: 5.6.50.0
TransferObjects:
- BlockTime: ''
  ChangedUTCTimestamp: 2024-05-27T08:38:34.9770000Z
  ForceCycle: ''
  Groups:
  - Items:
    - Direction: output
      LocalId: 737713000
      Name: Value
      _clrType:
      - inray.OPCRouter.PlugIns.Shared.DataChangeTrigger.DatachangeTriggerItem, inray.OPCRouter.PlugIns.Shared
  ItemAddress: PTime
  LocalId: 1866323804
  PlugIn: VariablesPlugInConfig
  PosX: 80
  PosY: 60
  TriggerType: OnEveryChange
  _clrType:
  - inray.OPCRouter.PlugIns.Shared.DataChangeTrigger.DatachangeTriggerConfigV2, inray.OPCRouter.PlugIns.Shared
- ChangedUTCTimestamp: 2024-05-27T08:39:45.1390000Z
  Groups:
  - Items:
    - Direction: input
      LocalId: 713674027
      Name: M
    Name: Variables
    _clrType:
    - inray.OPCRouter.BasePlugIn.Config.Calculator.TORechnerVariablesGroup, inray.OPCRouter4.BasePlugIn
  - Items:
    - Direction: output
      LocalId: 1572283772
      Name: Output value
    Name: Result
    _clrType:
    - inray.OPCRouter.BasePlugIn.Config.Calculator.TORechnerResultGroup, inray.OPCRouter4.BasePlugIn
  LocalId: 1603390366
  PlugIn: BasePlugInConfig
  PosX: 800
  PosY: 20
  StringToParse: IF(M > 1, MAX(M - RANDBETWEEN(2, 8), 0), M)
  _clrType:
  - inray.OPCRouter.BasePlugIn.Config.Calculator.TORechnerTransferObjectConfig, inray.OPCRouter4.BasePlugIn
- ChangedUTCTimestamp: 2024-05-27T09:05:41.8530000Z
  ConfigType: 3001
  Groups:
  - Items:
    - ForceType: Default
      LocalId: 2059240501
      Name: bp=Objects/2:Maschinen/2:RO1/2:Durchflussmenge;
      OPCAddress: bp=Objects/2:Maschinen/2:RO1/2:Durchflussmenge;
      _clrType:
      - inray.OPCRouter.OPCPlugIn.Runtime.OPCTransferObjectItem, inray.OPCRouter4.OPCPlugIn
    Name: Items
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcRegularItemsGroup, inray.OPCRouter4.OPCPlugIn
  - Name: Value Timestamp
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcValueTimestampGroup, inray.OPCRouter4.OPCPlugIn
  - Name: Quality ID
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcQualityIntGroup, inray.OPCRouter4.OPCPlugIn
  - Name: Quality string
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcQualityStringGroup, inray.OPCRouter4.OPCPlugIn
  LocalId: 2001160204
  PlugIn: UAServer2408301209-223846937-1801FB34-00002707
  PlugInType: 3100
  PosX: 400
  PosY: 40
  _clrType:
  - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObjectConfig, inray.OPCRouter4.OPCPlugIn
- ChangedUTCTimestamp: 2024-05-27T09:05:41.8530000Z
  ConfigType: 3001
  Groups:
  - Items:
    - ForceType: Default
      LocalId: 1904181876
      Name: bp=Objects/2:Maschinen/2:RO1/2:Durchflussmenge;
      OPCAddress: bp=Objects/2:Maschinen/2:RO1/2:Durchflussmenge;
      _clrType:
      - inray.OPCRouter.OPCPlugIn.Runtime.OPCTransferObjectItem, inray.OPCRouter4.OPCPlugIn
    Name: Items
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcRegularItemsGroup, inray.OPCRouter4.OPCPlugIn
  - Name: Value Timestamp
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcValueTimestampGroup, inray.OPCRouter4.OPCPlugIn
  - Name: Quality ID
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcQualityIntGroup, inray.OPCRouter4.OPCPlugIn
  - Name: Quality string
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcQualityStringGroup, inray.OPCRouter4.OPCPlugIn
  LocalId: 1015121415
  PlugIn: UAServer2408301209-223846937-1801FB34-00002707
  PlugInType: 3100
  PosX: 1020
  PosY: 360
  _clrType:
  - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObjectConfig, inray.OPCRouter4.OPCPlugIn
- ChangedUTCTimestamp: 2024-09-10T10:50:11.7730000Z
  Groups:
  - Items:
    - Direction: output
      LocalId: 1908734073
      Name: 0.000001
      VariantValue:
        Value: 0.000001
        VariantType: System.String, System.Private.CoreLib
        _clrType:
        - inray.SDK.Data.YamlSerializer.YamlVariant, inray.SDK.Data
      _clrType:
      - inray.OPCRouter.BasePlugIn.Config.Static.StaticTransferObjectItem, inray.OPCRouter4.BasePlugIn
  LocalId: 1076484560
  PlugIn: BasePlugInConfig
  PosX: 940
  PosY: 580
  _clrType:
  - inray.OPCRouter.BasePlugIn.Config.Static.StaticTransferObjectConfig, inray.OPCRouter4.BasePlugIn
- ChangedUTCTimestamp: 2024-05-27T08:53:45.0830000Z
  Groups:
  - Items:
    - Direction: input
      LocalId: 1767872708
      Name: T
    Name: Variables
    _clrType:
    - inray.OPCRouter.BasePlugIn.Config.Calculator.TORechnerVariablesGroup, inray.OPCRouter4.BasePlugIn
  - Items:
    - Direction: output
      LocalId: 1514016551
      Name: Ausgabewert
    Name: Result
    _clrType:
    - inray.OPCRouter.BasePlugIn.Config.Calculator.TORechnerResultGroup, inray.OPCRouter4.BasePlugIn
  LocalId: 2006407044
  PlugIn: BasePlugInConfig
  PosX: 60
  PosY: 300
  StringToParse: IF(MOD(RANDBETWEEN(0,1000), 2) > 0,     T - (RANDBETWEEN(0, 10) / 1000),     T + (RANDBETWEEN(0, 10) / 1000) )
  _clrType:
  - inray.OPCRouter.BasePlugIn.Config.Calculator.TORechnerTransferObjectConfig, inray.OPCRouter4.BasePlugIn
- ChangedUTCTimestamp: 2024-10-15T11:18:27.5850000Z
  Groups:
  - Items:
    - Direction: input
      LocalId: 2061007296
      Name: T
    Name: Variablen
    _clrType:
    - inray.OPCRouter.BasePlugIn.Config.Calculator.TORechnerVariablesGroup, inray.OPCRouter4.BasePlugIn
  - Items:
    - Direction: output
      LocalId: 1343061374
      Name: Ausgabewert
    Name: Ergebnis
    _clrType:
    - inray.OPCRouter.BasePlugIn.Config.Calculator.TORechnerResultGroup, inray.OPCRouter4.BasePlugIn
  LocalId: 1450406381
  PlugIn: BasePlugInConfig
  PosX: 540
  PosY: 560
  StringToParse: MIN(MAX(T, 0), 0.1)
  _clrType:
  - inray.OPCRouter.BasePlugIn.Config.Calculator.TORechnerTransferObjectConfig, inray.OPCRouter4.BasePlugIn
