ChangedUtcTimestamp: 2024-06-24T07:30:44.0410000Z
ConnectionLines:
- ItemStart: 1173257311
  ItemStop: 1263925604
- ItemStart: 71819427
  ItemStop: 289250303
PublishedUtcTimestamp: 0001-01-01T00:00:00.0000000Z
SavedInVersion: 5.6.50.0
TransferObjects:
- BlockTime: ''
  ChangedUTCTimestamp: 2024-05-27T08:57:13.4980000Z
  ForceCycle: ''
  Groups:
  - Items:
    - Direction: output
      LocalId: 1359976117
      Name: Value
      _clrType:
      - inray.OPCRouter.PlugIns.Shared.DataChangeTrigger.DatachangeTriggerItem, inray.OPCRouter.PlugIns.Shared
  ItemAddress: RTime
  LocalId: 1922654029
  PlugIn: VariablesPlugInConfig
  PosX: 360
  PosY: 220
  TriggerType: OnEveryChange
  _clrType:
  - inray.OPCRouter.PlugIns.Shared.DataChangeTrigger.DatachangeTriggerConfigV2, inray.OPCRouter.PlugIns.Shared
- ChangedUTCTimestamp: 2024-05-27T08:57:38.6880000Z
  Groups:
  - Items:
    - Direction: input
      LocalId: 1263925604
      Name: T
    Name: Variables
    _clrType:
    - inray.OPCRouter.BasePlugIn.Config.Calculator.TORechnerVariablesGroup, inray.OPCRouter4.BasePlugIn
  - Items:
    - Direction: output
      LocalId: 71819427
      Name: Output value
    Name: Result
    _clrType:
    - inray.OPCRouter.BasePlugIn.Config.Calculator.TORechnerResultGroup, inray.OPCRouter4.BasePlugIn
  LocalId: 1318592477
  PlugIn: BasePlugInConfig
  PosX: 600
  PosY: 440
  StringToParse: IF(T < 85, MIN(90, T + (RANDBETWEEN(0, 100) / 1000)), MAX(85, MIN(95, T + RANDBETWEEN(-2, 2))))
  _clrType:
  - inray.OPCRouter.BasePlugIn.Config.Calculator.TORechnerTransferObjectConfig, inray.OPCRouter4.BasePlugIn
- ChangedUTCTimestamp: 2024-05-27T09:06:47.0920000Z
  ConfigType: 3001
  Groups:
  - Items:
    - ForceType: Default
      LocalId: 1173257311
      Name: bp=Objects/2:Maschinen/2:RO1/2:Temperatur;
      OPCAddress: bp=Objects/2:Maschinen/2:RO1/2:Temperatur;
      _clrType:
      - inray.OPCRouter.OPCPlugIn.Runtime.OPCTransferObjectItem, inray.OPCRouter4.OPCPlugIn
    Name: Items
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcRegularItemsGroup, inray.OPCRouter4.OPCPlugIn
  - Name: Value Timestamp
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcValueTimestampGroup, inray.OPCRouter4.OPCPlugIn
  - Name: Quality ID
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcQualityIntGroup, inray.OPCRouter4.OPCPlugIn
  - Name: Quality string
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcQualityStringGroup, inray.OPCRouter4.OPCPlugIn
  LocalId: 318317907
  PlugIn: UAServer2408301209-223846937-1801FB34-00002707
  PlugInType: 3100
  PosX: 200
  PosY: 440
  _clrType:
  - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObjectConfig, inray.OPCRouter4.OPCPlugIn
- ChangedUTCTimestamp: 2024-05-27T09:06:47.0920000Z
  ConfigType: 3001
  Groups:
  - Items:
    - ForceType: Default
      LocalId: 289250303
      Name: bp=Objects/2:Maschinen/2:RO1/2:Temperatur;
      OPCAddress: bp=Objects/2:Maschinen/2:RO1/2:Temperatur;
      _clrType:
      - inray.OPCRouter.OPCPlugIn.Runtime.OPCTransferObjectItem, inray.OPCRouter4.OPCPlugIn
    Name: Items
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcRegularItemsGroup, inray.OPCRouter4.OPCPlugIn
  - Name: Value Timestamp
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcValueTimestampGroup, inray.OPCRouter4.OPCPlugIn
  - Name: Quality ID
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcQualityIntGroup, inray.OPCRouter4.OPCPlugIn
  - Name: Quality string
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcQualityStringGroup, inray.OPCRouter4.OPCPlugIn
  LocalId: 745138093
  PlugIn: UAServer2408301209-223846937-1801FB34-00002707
  PlugInType: 3100
  PosX: 1420
  PosY: 480
  _clrType:
  - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObjectConfig, inray.OPCRouter4.OPCPlugIn
