ChangedUtcTimestamp: 0001-01-01T00:00:00.0000000Z
ConnectionLines:
- ItemStart: 1378522798
  ItemStop: 744337058
- ItemStart: 969128918
  ItemStop: 531311988
- ItemStart: 495467691
  ItemStop: 1461217675
- ItemStart: 1378492993
  ItemStop: 1502433760
- ItemStart: 1378492993
  ItemStop: 221389140
- ItemStart: 264532120
  ItemStop: 98449263
- ItemStart: 1387556749
  ItemStop: 110160426
- ItemStart: 1354235767
  ItemStop: 338951821
- ItemStart: 1378492993
  ItemStop: 594181964
- ItemStart: 402390653
  ItemStop: 1274013745
PublishedUtcTimestamp: 0001-01-01T00:00:00.0000000Z
SavedInVersion: 5.6.50.0
TransferObjects:
- ChangedUTCTimestamp: 2023-09-28T07:44:32.0520000Z
  LocalId: 1683650385
  PlugIn: BasePlugInConfig
  PosX: 280
  PosY: 160
  _clrType:
  - inray.OPCRouter.BasePlugIn.Config.TimeTrigger.TimeTriggerConfig, inray.OPCRouter4.BasePlugIn
- ChangedUTCTimestamp: 2023-09-28T07:44:57.0520000Z
  Groups:
  - Items:
    - Direction: input
      LocalId: 744337058
      Name: Trigger
    - Direction: input
      LocalId: 1502433760
      Name: Störung
    - Direction: input
      LocalId: 1461217675
      Name: Fortschritt
    Name: Variablen
    _clrType:
    - inray.OPCRouter.BasePlugIn.Config.Calculator.TORechnerVariablesGroup, inray.OPCRouter4.BasePlugIn
  - Items:
    - Direction: output
      LocalId: 969128918
      Name: Ausgabewert
    Name: Ergebnis
    _clrType:
    - inray.OPCRouter.BasePlugIn.Config.Calculator.TORechnerResultGroup, inray.OPCRouter4.BasePlugIn
  LocalId: 2131835768
  PlugIn: BasePlugInConfig
  PosX: 460
  PosY: 360
  StringToParse: IF(Störung = True, Trigger, Trigger + 1)
  _clrType:
  - inray.OPCRouter.BasePlugIn.Config.Calculator.TORechnerTransferObjectConfig, inray.OPCRouter4.BasePlugIn
- ChangedUTCTimestamp: 2023-09-28T07:45:06.3250000Z
  Groups:
  - Items:
    - LocalId: 1378522798
      Name: trigger
      VariableId: 544c610c-0da2-4d0f-9868-33eb9693946e
      _clrType:
      - inray.OPCRouter.VariablesPlugIn.Runtime.VariablesTransferObjectItem, inray.OPCRouter4.VariablesPlugIn
  LocalId: 1933145763
  PlugIn: VariablesPlugInConfig
  PosX: 240
  PosY: 340
  _clrType:
  - inray.OPCRouter.VariablesPlugIn.Config.VariablesTransferObjectConfig, inray.OPCRouter4.VariablesPlugIn
- ChangedUTCTimestamp: 2023-09-28T07:47:31.6760000Z
  Groups:
  - Items:
    - LocalId: 531311988
      Name: trigger
      VariableId: 544c610c-0da2-4d0f-9868-33eb9693946e
      _clrType:
      - inray.OPCRouter.VariablesPlugIn.Runtime.VariablesTransferObjectItem, inray.OPCRouter4.VariablesPlugIn
  LocalId: 1632759635
  PlugIn: VariablesPlugInConfig
  PosX: 1080
  PosY: 460
  _clrType:
  - inray.OPCRouter.VariablesPlugIn.Config.VariablesTransferObjectConfig, inray.OPCRouter4.VariablesPlugIn
- ChangedUTCTimestamp: 2023-09-28T08:09:33.8000000Z
  ConfigType: 3001
  Groups:
  - Items:
    - ForceType: Default
      LocalId: 495467691
      Name: bp=Objects/2:Maschinen/2:H01/2:Fortschritt;
      OPCAddress: bp=Objects/2:Maschinen/2:H01/2:Fortschritt;
      _clrType:
      - inray.OPCRouter.OPCPlugIn.Runtime.OPCTransferObjectItem, inray.OPCRouter4.OPCPlugIn
    - ForceType: Default
      LocalId: 1378492993
      Name: bp=Objects/2:Maschinen/2:H01/2:Störungsbit;
      OPCAddress: bp=Objects/2:Maschinen/2:H01/2:Störungsbit;
      _clrType:
      - inray.OPCRouter.OPCPlugIn.Runtime.OPCTransferObjectItem, inray.OPCRouter4.OPCPlugIn
    - ForceType: Default
      LocalId: 1387556749
      Name: bp=Objects/2:Maschinen/2:H01/2:Temperatur;
      OPCAddress: bp=Objects/2:Maschinen/2:H01/2:Temperatur;
      _clrType:
      - inray.OPCRouter.OPCPlugIn.Runtime.OPCTransferObjectItem, inray.OPCRouter4.OPCPlugIn
    - ForceType: Default
      LocalId: 1354235767
      Name: bp=Objects/2:Maschinen/2:H01/2:Drehzahl;
      OPCAddress: bp=Objects/2:Maschinen/2:H01/2:Drehzahl;
      _clrType:
      - inray.OPCRouter.OPCPlugIn.Runtime.OPCTransferObjectItem, inray.OPCRouter4.OPCPlugIn
    Name: Items
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcRegularItemsGroup, inray.OPCRouter4.OPCPlugIn
  - Name: Value Timestamp
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcValueTimestampGroup, inray.OPCRouter4.OPCPlugIn
  - Name: Quality-ID
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcQualityIntGroup, inray.OPCRouter4.OPCPlugIn
  - Name: Quality-String
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcQualityStringGroup, inray.OPCRouter4.OPCPlugIn
  LocalId: 1705164268
  PlugIn: UAServer2408301209-223846937-1801FB34-00002707
  PlugInType: 3100
  PosX: 20
  PosY: 540
  _clrType:
  - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObjectConfig, inray.OPCRouter4.OPCPlugIn
- ChangedUTCTimestamp: 2023-09-28T08:11:27.0800000Z
  Groups:
  - Items:
    - Direction: input
      LocalId: 221389140
      Name: Störung
    - Direction: input
      LocalId: 110160426
      Name: Temperatur
    Name: Variablen
    _clrType:
    - inray.OPCRouter.BasePlugIn.Config.Calculator.TORechnerVariablesGroup, inray.OPCRouter4.BasePlugIn
  - Items:
    - Direction: output
      LocalId: 264532120
      Name: Ausgabewert
    Name: Ergebnis
    _clrType:
    - inray.OPCRouter.BasePlugIn.Config.Calculator.TORechnerResultGroup, inray.OPCRouter4.BasePlugIn
  LocalId: 194301596
  PlugIn: BasePlugInConfig
  PosX: 460
  PosY: 600
  StringToParse: IF(Störung = True, IF(Temperatur > 14, Temperatur - RANDBETWEEN(4, 7), Temperatur), Temperatur)
  _clrType:
  - inray.OPCRouter.BasePlugIn.Config.Calculator.TORechnerTransferObjectConfig, inray.OPCRouter4.BasePlugIn
- ChangedUTCTimestamp: 2023-09-28T08:18:20.7600000Z
  ConfigType: 3001
  Groups:
  - Items:
    - ForceType: Default
      LocalId: 98449263
      Name: bp=Objects/2:Maschinen/2:H01/2:Temperatur;
      OPCAddress: bp=Objects/2:Maschinen/2:H01/2:Temperatur;
      _clrType:
      - inray.OPCRouter.OPCPlugIn.Runtime.OPCTransferObjectItem, inray.OPCRouter4.OPCPlugIn
    - ForceType: Default
      LocalId: 1274013745
      Name: bp=Objects/2:Maschinen/2:H01/2:Drehzahl;
      OPCAddress: bp=Objects/2:Maschinen/2:H01/2:Drehzahl;
      _clrType:
      - inray.OPCRouter.OPCPlugIn.Runtime.OPCTransferObjectItem, inray.OPCRouter4.OPCPlugIn
    Name: Items
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcRegularItemsGroup, inray.OPCRouter4.OPCPlugIn
  - Name: Value Timestamp
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcValueTimestampGroup, inray.OPCRouter4.OPCPlugIn
  - Name: Quality-ID
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcQualityIntGroup, inray.OPCRouter4.OPCPlugIn
  - Name: Quality-String
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcQualityStringGroup, inray.OPCRouter4.OPCPlugIn
  LocalId: 651217475
  PlugIn: UAServer2408301209-223846937-1801FB34-00002707
  PlugInType: 3100
  PosX: 1340
  PosY: 720
  _clrType:
  - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObjectConfig, inray.OPCRouter4.OPCPlugIn
- ChangedUTCTimestamp: 2023-10-05T13:16:33.6370000Z
  Groups:
  - Items:
    - Direction: input
      LocalId: 338951821
      Name: RPM
    - Direction: input
      LocalId: 594181964
      Name: S
    Name: Variables
    _clrType:
    - inray.OPCRouter.BasePlugIn.Config.Calculator.TORechnerVariablesGroup, inray.OPCRouter4.BasePlugIn
  - Items:
    - Direction: output
      LocalId: 402390653
      Name: Output value
    Name: Result
    _clrType:
    - inray.OPCRouter.BasePlugIn.Config.Calculator.TORechnerResultGroup, inray.OPCRouter4.BasePlugIn
  LocalId: 242887383
  PlugIn: BasePlugInConfig
  PosX: 460
  PosY: 780
  StringToParse: IF(S = True, MAX(RPM - RANDBETWEEN(15, 45), 1), RPM)
  _clrType:
  - inray.OPCRouter.BasePlugIn.Config.Calculator.TORechnerTransferObjectConfig, inray.OPCRouter4.BasePlugIn
