name: Create release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the release (e.g. v1.0.1)"
        required: true

permissions:
  contents: write

jobs:
  create-zip-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Create ZIP without .git and .github
        run: |
          zip -r solutions.zip . \
            -x ".git/*" ".github/*"

      - name: Create or update release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: solutions.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
