ChangedUtcTimestamp: 0001-01-01T00:00:00.0000000Z
ConnectionLines:
- ItemStart: 701975193
  ItemStop: 1048629384
- ItemStart: 2110637678
  ItemStop: 810923176
PublishedUtcTimestamp: 0001-01-01T00:00:00.0000000Z
SavedInVersion: 5.6.50.0
TransferObjects:
- ChangedUTCTimestamp: 2023-09-28T05:38:19.3780000Z
  Groups:
  - Items:
    - Direction: input
      LocalId: 810923176
      Name: Füllstand
    Name: Variables
    _clrType:
    - inray.OPCRouter.BasePlugIn.Config.Calculator.TORechnerVariablesGroup, inray.OPCRouter4.BasePlugIn
  - Items:
    - Direction: output
      LocalId: 701975193
      Name: Output value
    Name: Result
    _clrType:
    - inray.OPCRouter.BasePlugIn.Config.Calculator.TORechnerResultGroup, inray.OPCRouter4.BasePlugIn
  LocalId: 243350410
  PlugIn: BasePlugInConfig
  PosX: 480
  PosY: 240
  StringToParse: MAX(IF(Füllstand = 0, 100, Füllstand - (RANDBETWEEN(1, 3) / 10)), 0)
  _clrType:
  - inray.OPCRouter.BasePlugIn.Config.Calculator.TORechnerTransferObjectConfig, inray.OPCRouter4.BasePlugIn
- ChangedUTCTimestamp: 2023-09-28T05:43:25.0630000Z
  ConfigType: 3001
  Groups:
  - Items:
    - ForceType: Default
      LocalId: 1048629384
      Name: bp=Objects/2:Maschinen/2:H03/2:Füllstand;
      OPCAddress: bp=Objects/2:Maschinen/2:H03/2:Füllstand;
      _clrType:
      - inray.OPCRouter.OPCPlugIn.Runtime.OPCTransferObjectItem, inray.OPCRouter4.OPCPlugIn
    Name: Items
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcRegularItemsGroup, inray.OPCRouter4.OPCPlugIn
  - Name: Value Timestamp
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcValueTimestampGroup, inray.OPCRouter4.OPCPlugIn
  - Name: Quality ID
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcQualityIntGroup, inray.OPCRouter4.OPCPlugIn
  - Name: Quality string
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcQualityStringGroup, inray.OPCRouter4.OPCPlugIn
  LocalId: 1950716370
  PlugIn: UAServer2408301209-223846937-1801FB34-00002707
  PlugInType: 3100
  PosX: 1060
  PosY: 280
  _clrType:
  - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObjectConfig, inray.OPCRouter4.OPCPlugIn
- BlockTime: ''
  ChangedUTCTimestamp: 2023-09-28T08:30:41.8930000Z
  ForceCycle: ''
  Groups:
  - Items:
    - Direction: output
      LocalId: 1933270662
      Name: Value
      _clrType:
      - inray.OPCRouter.PlugIns.Shared.DataChangeTrigger.DatachangeTriggerItem, inray.OPCRouter.PlugIns.Shared
  ItemAddress: trigger3
  LocalId: 1630804447
  PlugIn: VariablesPlugInConfig
  PosX: 120
  PosY: 40
  TriggerType: OnEveryChange
  _clrType:
  - inray.OPCRouter.PlugIns.Shared.DataChangeTrigger.DatachangeTriggerConfigV2, inray.OPCRouter.PlugIns.Shared
- ChangedUTCTimestamp: 2023-10-02T08:32:27.4930000Z
  ConfigType: 3001
  Groups:
  - Items:
    - ForceType: Default
      LocalId: 2110637678
      Name: bp=Objects/2:Maschinen/2:H03/2:Füllstand;
      OPCAddress: bp=Objects/2:Maschinen/2:H03/2:Füllstand;
      _clrType:
      - inray.OPCRouter.OPCPlugIn.Runtime.OPCTransferObjectItem, inray.OPCRouter4.OPCPlugIn
    Name: Items
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcRegularItemsGroup, inray.OPCRouter4.OPCPlugIn
  - Name: Value Timestamp
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcValueTimestampGroup, inray.OPCRouter4.OPCPlugIn
  - Name: Quality ID
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcQualityIntGroup, inray.OPCRouter4.OPCPlugIn
  - Name: Quality string
    _clrType:
    - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObject.OpcQualityStringGroup, inray.OPCRouter4.OPCPlugIn
  LocalId: 37744817
  PlugIn: UAServer2408301209-223846937-1801FB34-00002707
  PlugInType: 3100
  PosX: 40
  PosY: 240
  _clrType:
  - inray.OPCRouter.OPCPlugIn.Config.OPCTransferObjectConfig, inray.OPCRouter4.OPCPlugIn
